root_path: ""

dataset:
  data_path: "${root_path}/data/own/data.csv"

training:
  gpu: 0
  epochs: 100
  batch_size: 8
  num_workers: 0
  seed:
  lr: 0.001
  weight_decay: 0
  factor: 0.1
  patience: 10
  threshold: 0.0001

model:
  name: ANN
  n_layers: 3
  n_features: 881
  n_classes: 2
  hidden_size: 256
  dropout: 0.1
  time_steps: 10

#sweep:
#  method: random
#  parameters:
#      model:
#        parameters:
#          n_layers:
#            distribution: int_uniform
#            min: 1
#            max: 5
#          n_features:
#            distribution: int_uniform
#            min: 1
#            max: 50
