# Sweep template config

# "online" to send data to wandb server
# "offline" to save data locally, and optionally sync them later with `wandb sync`
# "disabled" to mock the wandb API and not store any data
wandb_mode: "online"

name: LSTM_test

dataset:
  data_path: "${root_path}/data/own/data.csv"

training:
  gpu: 0
  epochs: 50
  batch_size: 256
  num_workers: 0
  seed:
  # lr: 0.001
  weight_decay: 0
  factor: 0.1
  # patience: 10
  threshold: 0.0001
  loss: "reward"

model:
  name: LSTM
  # n_layers: 3
  n_features: 897
  n_classes: 2
  # hidden_size: 256
  # dropout: 0.1

# https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
sweep:
  # Max number of runs, if not specified, sweep will run until stopped
  run_cap: 100

  # early stopping
  # https://docs.wandb.ai/guides/sweeps/define-sweep-configuration#early_terminate
  # https://open.gitcode.host/wandb-docs/sweeps/configuration.html#stopping-criteria
  early_terminate:
    type: hyperband
    s: 2
    eta: 3
    max_iter: 27

  # grid, random, bayes
  # Random and Bayesian searches will run forever or until the run_cap is reached.
  # Grid searches will run forever if searching in continuous space
  method: bayes

  # required for bayes
  metric:
    # name: Test_acc
    # goal: maximize
    name: val_bet_reward
    goal: maximize

  parameters:
      training:
        parameters:
          lr:
            distribution: uniform
            min: 0.0001
            max: 0.5

          patience:
            distribution: int_uniform
            min: 8
            max: 20

      model:
        parameters:
          n_layers:
            distribution: int_uniform
            min: 3
            max: 20

          hidden_size:
            values: [128, 256, 512, 1024, 2048]
