# Single run template config

# "online" to send data to wandb server
# "offline" to save data locally, and optionally sync them later with `wandb sync`
# "disabled" to mock the wandb API and not store any data
wandb_mode: "disabled"

name: template

dataset:
  data_path: "${root_path}/data/own/data.csv"

training:
  gpu: 0
  epochs: 100
  batch_size: 256
  num_workers: 0
  seed:
  lr: 0.001
  weight_decay: 0
  factor: 0.1
  patience: 10
  threshold: 0.0001
  loss: "cross_entropy"

model:
  name: LSTM
  n_layers: 3
  n_features: 893
  n_classes: 2
  hidden_size: 16
  dropout: 0.1
